[build]
  command = "npm run build"
  publish = "dist"
[[redirects]]
from = "https://spektordev.netlify.com/*"
to = "https://www.spektor.dev/:splat"
status = 301
force = true
[functions]
    external_node_modules = ["astro"]